/* Generated By:JavaCC: Do not edit this line. LanguageConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LanguageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FALSE = 5;
  /** RegularExpression Id. */
  int LETTER = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int EQUAL = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int EQUAL2 = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int SKIPCOM = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int THEN = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int LEFTBRAC = 22;
  /** RegularExpression Id. */
  int RIGHTBRAC = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"ff\"",
    "<LETTER>",
    "<DIGIT>",
    "\":=\"",
    "\";\"",
    "\"+\"",
    "\"-\"",
    "\"tt\"",
    "\"==\"",
    "\"!\"",
    "\"^\"",
    "\"skip\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"(\"",
    "\")\"",
  };

}
